### ISSUE TITLE
[REQ] OpenApis support

### ISSUE THREAD

**Issue by klausmyrseth** [spincast/spincast-framework#1]
I been using spincast for a while and I am enjoying the framework quite a bit ;)

I only miss one feature to make spincast a proper goto for all my rest and websocket needs ;) and its https://github.com/OAI/OpenAPI-Specification support.

This will make it so much easier when you are documenting your rest apis!

**Comment by electrotype** [comment]
Hi,

What approach do you have in mind? 

A _top-down_ one where you write the specifications file first and a plugin would generate the routes and controllers based on it ? Or a _bottom-up_ one where you would have to annotate your routes (or use a specific comments format) and have the specifications file automatically generated?

Since Spincast doesn't impose a rigid app structure, I guess a _bottom-up_ approach would make more sense.

I'm currently working on a new project (based on Spincast!), so I have to say I don't have too much time to work on new Spincast features. But this is a good suggestion and I'll work on it when I can! Thanks.

**Comment by klausmyrseth** [comment]
I'm thinking it should be quite possible to read the defined routes and so on... Since you can mix and match your injection modules to make the apis it would be a VERY nice feature if you can get a openapi.yaml definition off the current state of the hosted spincast app.

Then its also SO much easier when you want to use the google openapi gateway to expose your rest apis :)

**Comment by electrotype** [comment]
OpenAPI support (bottom up) added: [Spincast OpenAPI bottom up plugin](https://www.spincast.org/plugins/spincast-openapi-bottomup)
